#!/bin/bash

set -euo pipefail

export CHRONOS_PATH="${CHRONOS_PATH:-$HOME/.local/share/chronos}"

source "$CHRONOS_PATH/lib/functions.sh"

source "$CHRONOS_PATH/scripts/00-prerequisites/gum-install.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/set-variables.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/system-update.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/pacman-config.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/base-packages.sh"

source "$CHRONOS_PATH/scripts/01-system/kernel-update.sh"

gum_style --foreground="#50fa7b" "Installation complete!"
echo
gum_style --foreground="#f1fa8c" "Please reboot your system to complete the installation:"
gum_style --foreground="#8be9fd" "sudo reboot"