#!/bin/bash

set -euo pipefail

export CHRONOS_PATH="${CHRONOS_PATH:-$HOME/.local/share/chronos}"


source "$CHRONOS_PATH/scripts/00-prerequisites/gum-install.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/set-variables.sh"

source "$CHRONOS_PATH/lib/functions.sh"

source "$CHRONOS_PATH/scripts/00-prerequisites/system-update.sh"
source "$CHRONOS_PATH/scripts/00-prerequisites/enable-multilib.sh"

gum_style --foreground="#ff79c6" --bold --italic --width=58 --align="center" \
	"Installation complete! Rebooting in 5 seconds... Press any key to cancel."

read -t 5 -n 1 key
if [[ $key ]]; then
    gum_style --foreground="#50fa7b" --bold --italic --width=58 --align="center" \
		"Reboot canceled."
    exit 0
fi
sleep 5
sudo reboot now