run_logged $CHRONOS_INSTALL/config/config.sh
run_logged $CHRONOS_INSTALL/config/git.sh
run_logged $CHRONOS_INSTALL/config/gpg.sh
run_logged $CHRONOS_INSTALL/config/timezones.sh
run_logged $CHRONOS_INSTALL/config/increase-sudo-tries.sh
run_logged $CHRONOS_INSTALL/config/increase-lockout-limit.sh
run_logged $CHRONOS_INSTALL/config/ssh-flakiness.sh
run_logged $CHRONOS_INSTALL/config/detect-keyboard-layout.sh
run_logged $CHRONOS_INSTALL/config/xcompose.sh
run_logged $CHRONOS_INSTALL/config/mise-developer.sh
run_logged $CHRONOS_INSTALL/config/fix-powerprofilesctl-shebang.sh
run_logged $CHRONOS_INSTALL/config/docker.sh
run_logged $CHRONOS_INSTALL/config/mimetypes.sh
run_logged $CHRONOS_INSTALL/config/localdb.sh
run_logged $CHRONOS_INSTALL/config/sudoless-asdcontrol.sh
run_logged $CHRONOS_INSTALL/config/hardware/network.sh
run_logged $CHRONOS_INSTALL/config/hardware/fix-fkeys.sh
run_logged $CHRONOS_INSTALL/config/hardware/bluetooth.sh
run_logged $CHRONOS_INSTALL/config/hardware/printer.sh
run_logged $CHRONOS_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $CHRONOS_INSTALL/config/hardware/ignore-power-button.sh
run_logged $CHRONOS_INSTALL/config/hardware/fix-f13-amd-audio-input.sh
run_logged $CHRONOS_INSTALL/config/hardware/fix-apple-bcm4360.sh
run_logged $CHRONOS_INSTALL/config/hardware/fix-apple-spi-keyboard.sh
run_logged $CHRONOS_INSTALL/config/hardware/fix-apple-t2.sh