# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Chronos defaults (but don't edit these directly!)
source = ~/.local/share/chronos/default/hypr/autostart.conf
source = ~/.local/share/chronos/default/hypr/bindings/media.conf
source = ~/.local/share/chronos/default/hypr/bindings/tiling.conf
source = ~/.local/share/chronos/default/hypr/bindings/utilities.conf
source = ~/.local/share/chronos/default/hypr/bindings/apps.conf
source = ~/.local/share/chronos/default/hypr/envs.conf
source = ~/.local/share/chronos/default/hypr/looknfeel.conf
source = ~/.local/share/chronos/default/hypr/input.conf
source = ~/.local/share/chronos/default/hypr/windows.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf