sudo yay -Syu --needed --noconfirm < /dev/tty \
autoconf-archive \
base \
base-devel \
broadcom-wl \
btrfs-progs \
dart \
dkms \
egl-wayland \
git \
gst-plugin-pipewire \
gtk4-layer-shell \
btop \
intltool \
iwd \
jdk-openjdk \
libpulse \
libsass \
libva-intel-driver \
libva-nvidia-driver \
limine \
limine-mkinitcpio-hook \
limine-snapper-sync \
linux-firmware \
macbook12-spi-driver-dkms \
nvidia-dkms \
nvidia-open-dkms \
nvidia-utils \
lib32-nvidia-utils \
pipewire \
pipewire-alsa \
pipewire-jack \
pipewire-pulse \
qt5-remoteobjects \
qt6-wayland \
sassc \
snapper \
webp-pixbuf-loader \
wget \
yay-debug \
zram-generator \
apple-bcm-firmware \
apple-t2-audio-config \
linux-t2 \
linux-t2-headers \
t2fanrd \
tiny-dfr 