# Menus
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle

# Toggle idling
bindd = SUPER CTRL, I, Toggle locking on idle, exec, chronos-toggle-idle

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, chronos-cmd-apple-display-brightness -5000
bindd = CTRL, F2, Apple Display brightness up, exec, chronos-cmd-apple-display-brightness +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, chronos-cmd-apple-display-brightness +60000

# Screenshots
bindd = , PRINT, Screenshot of region, exec, chronos-cmd-screenshot
bindd = SHIFT, PRINT, Screenshot of window, exec, chronos-cmd-screenshot window
bindd = CTRL, PRINT, Screenshot of display, exec, chronos-cmd-screenshot output

# Color picker
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a
